"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "pt" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navigation
    "nav.home": "Inicio",
    "nav.about": "Sobre Nos",
    "nav.services": "Servicos",
    "nav.sectors": "Setores",
    "nav.clients": "Clientes",
    "nav.team": "Equipa",
    "nav.contact": "Contacto",
    "nav.schedule": "Agendar Consulta",
    
    // Hero
    "hero.badge": "Desde 2021 em Lisboa",
    "hero.title1": "Contabilidade de ",
    "hero.title2": "Excelencia",
    "hero.title3": " para o Seu Negocio",
    "hero.description": "A Three Stars Accounting oferece servicos completos de contabilidade, auditoria, consultoria fiscal e recursos humanos. Apoiamos empresas de todos os setores a crescer de forma sustentavel.",
    "hero.highlight1": "Mais de 900 empresas confiam em nos",
    "hero.highlight2": "Servicos personalizados para cada setor",
    "hero.highlight3": "Equipa certificada e experiente",
    "hero.cta1": "Solicitar Proposta",
    "hero.cta2": "Conhecer Servicos",
    "hero.stat1": "Clientes Ativos",
    "hero.stat2": "Setores Servidos",
    "hero.stat3": "Anos de Experiencia",
    "hero.stat4": "Satisfacao",
    "hero.certified": "Certificados pela Ordem dos Contabilistas Certificados",
    "hero.yearsExp": "Anos de Experiencia",
    "hero.trustedBy": "Confiado por",
    "hero.businesses": "Empresas",
    
    // About
    "about.label": "Sobre Nos",
    "about.title": "Uma Historia de Crescimento e Confianca",
    "about.description": "A Three Stars Accounting nasceu com a missao de oferecer servicos de contabilidade e consultoria de excelencia, adaptados as necessidades especificas de cada cliente.",
    "about.growth": "O Nosso Crescimento",
    "about.milestone1.title": "Fundacao",
    "about.milestone1.desc": "Inicio das operacoes em Lisboa com foco em PMEs",
    "about.milestone2.title": "Expansao",
    "about.milestone2.desc": "Crescimento rapido e entrada em novos setores",
    "about.milestone3.title": "Consolidacao",
    "about.milestone3.desc": "Lideranca em servicos de RH e consultoria",
    "about.milestone4.title": "Excelencia",
    "about.milestone4.desc": "Reconhecimento como referencia no mercado",
    "about.companyInfo": "Informacoes da Empresa",
    "about.legalName": "Denominacao Social",
    "about.legalForm": "Forma Juridica",
    "about.legalFormValue": "Sociedade por Quotas",
    "about.capital": "Capital Social",
    "about.foundDate": "Data de Constituicao",
    "about.address": "Morada",
    "about.values": "Os Nossos Valores",
    "about.value1.title": "Integridade",
    "about.value1.desc": "Atuamos com total transparencia e etica inabalavel em todas as nossas relacoes comerciais. A confianca dos nossos clientes e construida atraves de praticas honestas e responsaveis.",
    "about.value2.title": "Competencia",
    "about.value2.desc": "A nossa equipa e composta por profissionais altamente qualificados, certificados pela Ordem dos Contabilistas, em constante atualizacao sobre legislacao fiscal e melhores praticas do setor.",
    "about.value3.title": "Proximidade",
    "about.value3.desc": "Oferecemos atendimento verdadeiramente personalizado, com disponibilidade permanente para os nossos clientes. Cada empresa e unica e merece atencao dedicada aos seus desafios especificos.",
    "about.value4.title": "Inovacao",
    "about.value4.desc": "Investimos continuamente nas mais modernas ferramentas digitais e metodologias de gestao. A tecnologia ao servico da eficiencia permite-nos oferecer solucoes ageis e precisas.",
    "about.mission": "A Nossa Missao",
    "about.missionDesc": "Proporcionar aos nossos clientes servicos de contabilidade e consultoria de alta qualidade, contribuindo para o sucesso e crescimento sustentavel dos seus negocios, mantendo sempre os mais elevados padroes eticos e profissionais.",
    
    // Services
    "services.label": "Os Nossos Servicos",
    "services.title": "Solucoes Completas para a Sua Empresa",
    "services.description": "Oferecemos uma gama completa de servicos de contabilidade e consultoria, adaptados as necessidades especificas de cada cliente e setor de atividade.",
    "services.learnMore": "Saber Mais",
    "services.accounting": "Contabilidade Geral",
    "services.accountingShort": "Gestao contabilistica completa",
    "services.tax": "Consultoria Fiscal",
    "services.taxShort": "Planeamento e otimizacao fiscal",
    "services.hr": "Recursos Humanos",
    "services.hrShort": "Gestao completa de pessoal",
    "services.audit": "Auditoria",
    "services.auditShort": "Revisao e certificacao de contas",
    "services.consulting": "Consultoria de Gestao",
    "services.consultingShort": "Apoio estrategico ao negocio",

    "services.company": "Criacao de Empresas",
    "services.companyShort": "Abertura e legalizacao",
    "services.outsourcing": "Outsourcing Financeiro",
    "services.outsourcingShort": "Externalizacao de processos",
    
    // Sectors
    "sectors.label": "Setores de Atividade",
    "sectors.title": "Experiencia em Multiplos Setores",
    "sectors.description": "Trabalhamos com empresas de diversos setores, oferecendo solucoes especializadas e adaptadas as especificidades de cada area de negocio.",
    "sectors.agriculture": "Agricultura",
    "sectors.agricultureDesc": "Producao agricola, pecuaria e agroindustria",
    "sectors.transport": "Transportes",
    "sectors.transportDesc": "Transporte de mercadorias e passageiros",
    "sectors.retail": "Retalho",
    "sectors.retailDesc": "Comercio a retalho e distribuicao",
    "sectors.ecommerce": "E-commerce",
    "sectors.ecommerceDesc": "Lojas online e marketplace",
    "sectors.realestate": "Imobiliario",
    "sectors.realestateDesc": "Promocao imobiliaria e gestao de imoveis",
    "sectors.restaurant": "Restauracao",
    "sectors.restaurantDesc": "Restaurantes, cafes e catering",
    "sectors.health": "Saude",
    "sectors.healthDesc": "Clinicas, farmacias e servicos medicos",
    "sectors.construction": "Construcao",
    "sectors.constructionDesc": "Obras publicas e privadas",
    "sectors.industry": "Industria",
    "sectors.industryDesc": "Producao industrial e transformacao",
    "sectors.education": "Educacao",
    "sectors.educationDesc": "Escolas, formacao e centros de estudo",
    "sectors.tourism": "Turismo",
    "sectors.tourismDesc": "Hoteis, alojamento local e agencias",
    "sectors.services": "Servicos",
    "sectors.servicesDesc": "Consultoria e servicos as empresas",
    "sectors.notFound": "Nao encontrou o seu setor? Contacte-nos para saber como podemos ajudar.",
    "sectors.cta": "Fale Connosco",
    "sectors.learnMore": "Saber mais",
    
    // Clients
    "clients.label": "Os Nossos Clientes",
    "clients.title": "Mais de 900 Empresas Confiam em Nos",
    "clients.description": "Desde startups a empresas estabelecidas, ajudamos negocios de todas as dimensoes a crescer de forma sustentavel.",
    "clients.supported": "Algumas das Empresas que Apoiamos",
    "clients.testimonials": "O Que Dizem os Nossos Clientes",
    "clients.activeClients": "Clientes Ativos",
    "clients.sectorsServed": "Setores Servidos",
    "clients.retention": "Taxa de Retencao",
    "clients.avgRating": "Avaliacao Media",
    
    // HR Services
    "hr.label": "Recursos Humanos",
    "hr.title": "Gestao de RH Simplificada",
    "hr.description": "Externalize a gestao de recursos humanos da sua empresa e foque-se no que realmente importa: o crescimento do seu negocio.",
    "hr.payroll": "Processamento Salarial",
    "hr.payrollDesc": "Gestao completa do processamento de salarios, incluindo calculo de vencimentos, subsidios, horas extras e descontos legais.",
    "hr.contracts": "Gestao Contratual",
    "hr.contractsDesc": "Elaboracao e gestao de contratos de trabalho, aditamentos, renovacoes e cessacoes contratuais.",
    "hr.social": "Seguranca Social",
    "hr.socialDesc": "Comunicacoes mensais a Seguranca Social, declaracoes de remuneracoes e gestao de contribuicoes.",
    "hr.absence": "Gestao de Ausencias",
    "hr.absenceDesc": "Controlo de ferias, faltas, licencas e baixas medicas, com relatorios detalhados.",
    "hr.legal": "Obrigacoes Legais",
    "hr.legalDesc": "Cumprimento de todas as obrigacoes legais: DMR, Relatorio Unico, FCT e outras declaracoes.",
    "hr.relations": "Relacoes Laborais",
    "hr.relationsDesc": "Apoio em processos disciplinares, negociacoes coletivas e resolucao de conflitos laborais.",
    "hr.reporting": "Reporting de RH",
    "hr.reportingDesc": "Relatorios analiticos sobre custos de pessoal, absentismo, rotatividade e indicadores de RH.",
    "hr.recruitment": "Recrutamento",
    "hr.recruitmentDesc": "Apoio no processo de recrutamento e selecao, incluindo publicacao de anuncios e triagem inicial.",
    "hr.benefits": "Vantagens do Nosso Servico de RH",
    "hr.benefit1": "Reducao de erros no processamento salarial",
    "hr.benefit2": "Cumprimento rigoroso dos prazos legais",
    "hr.benefit3": "Confidencialidade total dos dados",
    "hr.benefit4": "Acesso a plataforma online de RH",
    "hr.benefit5": "Apoio dedicado de especialistas",
    "hr.benefit6": "Atualizacao permanente da legislacao",
    "hr.outsourcedCompanies": "Empresas com gestao de RH externalizada",
    "hr.requestQuote": "Solicitar Orcamento de RH",
    "hr.receiptsProcessed": "Recibos processados mensalmente",
    "hr.compliance": "Conformidade legal garantida",
    "hr.responseTime": "Tempo medio de resposta",
    
    // Contact
    "contact.label": "Contacte-nos",
    "contact.title": "Estamos Aqui Para Ajudar",
    "contact.description": "Entre em contacto connosco para saber mais sobre os nossos servicos ou agendar uma consulta gratuita.",
    "contact.address": "Morada",
    "contact.phone": "Telefone",
    "contact.email": "Email",
    "contact.hours": "Horario",
    "contact.weekdays": "Segunda a Sexta: 9h00 - 18h00",
    "contact.saturday": "Sabado: 9h00 - 13h00",
    "contact.sendMessage": "Envie-nos uma Mensagem",
    "contact.messageSent": "Mensagem Enviada!",
    "contact.thankYou": "Obrigado pelo seu contacto. A nossa equipa ira responder dentro de 24 horas uteis.",
    "contact.fullName": "Nome Completo",
    "contact.company": "Empresa",
    "contact.serviceInterest": "Servico de Interesse",
    "contact.selectService": "Selecione um servico",
    "contact.message": "Mensagem",
    "contact.messagePlaceholder": "Descreva brevemente o que pretende...",
    "contact.required": "* Campos obrigatorios. Os seus dados serao tratados de acordo com a nossa politica de privacidade.",
    "contact.submit": "Enviar Mensagem",
    "contact.generalAccounting": "Contabilidade Geral",
    "contact.taxConsulting": "Consultoria Fiscal",
    "contact.humanResources": "Recursos Humanos",
    "contact.auditing": "Auditoria",
    "contact.companyCreation": "Criacao de Empresa",
    "contact.other": "Outro",
    
    // Team
    "team.label": "A Nossa Equipa",
    "team.title": "Conheca os Nossos Especialistas",
    "team.description": "Uma equipa de profissionais dedicados e certificados, prontos para ajudar o seu negocio a crescer com solucoes financeiras personalizadas.",
    "team.joinTitle": "Junte-se a Nossa Equipa",
    "team.joinDescription": "Estamos sempre a procura de talentos excecionais. Se partilha a nossa paixao por excelencia, entre em contacto.",
    "team.joinCta": "Ver Oportunidades",
    
    // Footer
    "footer.services": "Servicos",
    "footer.company": "Empresa",
    "footer.sectors": "Setores",
    "footer.legal": "Legal",
    "footer.description": "Servicos de contabilidade, auditoria e consultoria fiscal de excelencia para empresas em Portugal.",
    "footer.accounting": "Contabilidade",
    "footer.taxConsulting": "Consultoria Fiscal",
    "footer.hr": "Recursos Humanos",
    "footer.audit": "Auditoria",
    "footer.consulting": "Consultoria de Gestao",
    "footer.aboutUs": "Sobre Nos",
    "footer.team": "Equipa",
    "footer.careers": "Carreiras",
    "footer.news": "Noticias",
    "footer.agriculture": "Agricultura",
    "footer.transport": "Transportes",
    "footer.retail": "Retalho",
    "footer.ecommerce": "E-commerce",
    "footer.construction": "Construcao",
    "footer.privacy": "Politica de Privacidade",
    "footer.terms": "Termos de Servico",
    "footer.cookies": "Cookies",
    "footer.gdpr": "RGPD",
    "footer.rights": "Todos os direitos reservados.",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.sectors": "Sectors",
    "nav.clients": "Clients",
    "nav.team": "Team",
    "nav.contact": "Contact",
    "nav.schedule": "Schedule Consultation",
    
    // Hero
    "hero.badge": "Since 2021 in Lisbon",
    "hero.title1": "Accounting ",
    "hero.title2": "Excellence",
    "hero.title3": " for Your Business",
    "hero.description": "Three Stars Accounting offers comprehensive accounting, auditing, tax consulting and human resources services. We support companies across all sectors to grow sustainably.",
    "hero.highlight1": "Over 900 companies trust us",
    "hero.highlight2": "Customized services for each sector",
    "hero.highlight3": "Certified and experienced team",
    "hero.cta1": "Request Quote",
    "hero.cta2": "Learn About Services",
    "hero.stat1": "Active Clients",
    "hero.stat2": "Sectors Served",
    "hero.stat3": "Years of Experience",
    "hero.stat4": "Satisfaction",
    "hero.certified": "Certified by the Order of Certified Accountants",
    "hero.yearsExp": "Years Experience",
    "hero.trustedBy": "Trusted by",
    "hero.businesses": "Businesses",
    
    // About
    "about.label": "About Us",
    "about.title": "A Story of Growth and Trust",
    "about.description": "Three Stars Accounting was founded with the mission of offering excellent accounting and consulting services, tailored to the specific needs of each client.",
    "about.growth": "Our Growth",
    "about.milestone1.title": "Foundation",
    "about.milestone1.desc": "Started operations in Lisbon focused on SMEs",
    "about.milestone2.title": "Expansion",
    "about.milestone2.desc": "Rapid growth and entry into new sectors",
    "about.milestone3.title": "Consolidation",
    "about.milestone3.desc": "Leadership in HR and consulting services",
    "about.milestone4.title": "Excellence",
    "about.milestone4.desc": "Recognition as a market reference",
    "about.companyInfo": "Company Information",
    "about.legalName": "Legal Name",
    "about.legalForm": "Legal Form",
    "about.legalFormValue": "Limited Liability Company",
    "about.capital": "Share Capital",
    "about.foundDate": "Foundation Date",
    "about.address": "Address",
    "about.values": "Our Values",
    "about.value1.title": "Integrity",
    "about.value1.desc": "We act with total transparency and unwavering ethics in all our business relationships. Our clients' trust is built through honest and responsible practices.",
    "about.value2.title": "Competence",
    "about.value2.desc": "Our team is composed of highly qualified professionals, certified by the Order of Certified Accountants, constantly updated on tax legislation and industry best practices.",
    "about.value3.title": "Proximity",
    "about.value3.desc": "We offer truly personalized service with permanent availability for our clients. Each company is unique and deserves dedicated attention to its specific challenges.",
    "about.value4.title": "Innovation",
    "about.value4.desc": "We continuously invest in the most modern digital tools and management methodologies. Technology at the service of efficiency allows us to offer agile and accurate solutions.",
    "about.mission": "Our Mission",
    "about.missionDesc": "To provide our clients with high-quality accounting and consulting services, contributing to the success and sustainable growth of their businesses, while always maintaining the highest ethical and professional standards.",
    
    // Services
    "services.label": "Our Services",
    "services.title": "Complete Solutions for Your Company",
    "services.description": "We offer a complete range of accounting and consulting services, tailored to the specific needs of each client and sector.",
    "services.learnMore": "Learn More",
    "services.accounting": "General Accounting",
    "services.accountingShort": "Complete accounting management",
    "services.tax": "Tax Consulting",
    "services.taxShort": "Tax planning and optimization",
    "services.hr": "Human Resources",
    "services.hrShort": "Complete personnel management",
    "services.audit": "Auditing",
    "services.auditShort": "Account review and certification",
    "services.consulting": "Management Consulting",
    "services.consultingShort": "Strategic business support",

    "services.company": "Company Formation",
    "services.companyShort": "Opening and legalization",
    "services.outsourcing": "Financial Outsourcing",
    "services.outsourcingShort": "Process outsourcing",
    
    // Sectors
    "sectors.label": "Business Sectors",
    "sectors.title": "Experience Across Multiple Sectors",
    "sectors.description": "We work with companies from various sectors, offering specialized solutions adapted to the specificities of each business area.",
    "sectors.agriculture": "Agriculture",
    "sectors.agricultureDesc": "Agricultural production, livestock and agribusiness",
    "sectors.transport": "Transport",
    "sectors.transportDesc": "Goods and passenger transport",
    "sectors.retail": "Retail",
    "sectors.retailDesc": "Retail trade and distribution",
    "sectors.ecommerce": "E-commerce",
    "sectors.ecommerceDesc": "Online stores and marketplace",
    "sectors.realestate": "Real Estate",
    "sectors.realestateDesc": "Real estate development and management",
    "sectors.restaurant": "Restaurants",
    "sectors.restaurantDesc": "Restaurants, cafes and catering",
    "sectors.health": "Healthcare",
    "sectors.healthDesc": "Clinics, pharmacies and medical services",
    "sectors.construction": "Construction",
    "sectors.constructionDesc": "Public and private works",
    "sectors.industry": "Industry",
    "sectors.industryDesc": "Industrial production and transformation",
    "sectors.education": "Education",
    "sectors.educationDesc": "Schools, training and study centers",
    "sectors.tourism": "Tourism",
    "sectors.tourismDesc": "Hotels, local accommodation and agencies",
    "sectors.services": "Services",
    "sectors.servicesDesc": "Consulting and business services",
    "sectors.notFound": "Didn't find your sector? Contact us to learn how we can help.",
    "sectors.cta": "Talk to Us",
    "sectors.learnMore": "Learn more",
    
    // Clients
    "clients.label": "Our Clients",
    "clients.title": "Over 900 Companies Trust Us",
    "clients.description": "From startups to established companies, we help businesses of all sizes grow sustainably.",
    "clients.supported": "Some of the Companies We Support",
    "clients.testimonials": "What Our Clients Say",
    "clients.activeClients": "Active Clients",
    "clients.sectorsServed": "Sectors Served",
    "clients.retention": "Retention Rate",
    "clients.avgRating": "Average Rating",
    
    // HR Services
    "hr.label": "Human Resources",
    "hr.title": "Simplified HR Management",
    "hr.description": "Outsource your company's human resources management and focus on what really matters: growing your business.",
    "hr.payroll": "Payroll Processing",
    "hr.payrollDesc": "Complete salary processing management, including calculation of wages, allowances, overtime and legal deductions.",
    "hr.contracts": "Contract Management",
    "hr.contractsDesc": "Preparation and management of employment contracts, amendments, renewals and terminations.",
    "hr.social": "Social Security",
    "hr.socialDesc": "Monthly communications to Social Security, payroll declarations and contribution management.",
    "hr.absence": "Absence Management",
    "hr.absenceDesc": "Control of vacations, absences, leave and sick leave, with detailed reports.",
    "hr.legal": "Legal Obligations",
    "hr.legalDesc": "Compliance with all legal obligations: DMR, Single Report, FCT and other declarations.",
    "hr.relations": "Labor Relations",
    "hr.relationsDesc": "Support in disciplinary proceedings, collective negotiations and labor dispute resolution.",
    "hr.reporting": "HR Reporting",
    "hr.reportingDesc": "Analytical reports on personnel costs, absenteeism, turnover and HR indicators.",
    "hr.recruitment": "Recruitment",
    "hr.recruitmentDesc": "Support in the recruitment and selection process, including job posting and initial screening.",
    "hr.benefits": "Benefits of Our HR Service",
    "hr.benefit1": "Reduction of payroll processing errors",
    "hr.benefit2": "Strict compliance with legal deadlines",
    "hr.benefit3": "Complete data confidentiality",
    "hr.benefit4": "Access to online HR platform",
    "hr.benefit5": "Dedicated specialist support",
    "hr.benefit6": "Permanent legislation updates",
    "hr.outsourcedCompanies": "Companies with outsourced HR management",
    "hr.requestQuote": "Request HR Quote",
    "hr.receiptsProcessed": "Receipts processed monthly",
    "hr.compliance": "Guaranteed legal compliance",
    "hr.responseTime": "Average response time",
    
    // Contact
    "contact.label": "Contact Us",
    "contact.title": "We're Here to Help",
    "contact.description": "Contact us to learn more about our services or schedule a free consultation.",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.hours": "Hours",
    "contact.weekdays": "Monday to Friday: 9am - 6pm",
    "contact.saturday": "Saturday: 9am - 1pm",
    "contact.sendMessage": "Send Us a Message",
    "contact.messageSent": "Message Sent!",
    "contact.thankYou": "Thank you for your contact. Our team will respond within 24 business hours.",
    "contact.fullName": "Full Name",
    "contact.company": "Company",
    "contact.serviceInterest": "Service of Interest",
    "contact.selectService": "Select a service",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Briefly describe what you need...",
    "contact.required": "* Required fields. Your data will be processed according to our privacy policy.",
    "contact.submit": "Send Message",
    "contact.generalAccounting": "General Accounting",
    "contact.taxConsulting": "Tax Consulting",
    "contact.humanResources": "Human Resources",
    "contact.auditing": "Auditing",
    "contact.companyCreation": "Company Creation",
    "contact.other": "Other",
    
    // Team
    "team.label": "Our Team",
    "team.title": "Meet Our Specialists",
    "team.description": "A team of dedicated and certified professionals, ready to help your business grow with personalized financial solutions.",
    "team.joinTitle": "Join Our Team",
    "team.joinDescription": "We're always looking for exceptional talent. If you share our passion for excellence, get in touch.",
    "team.joinCta": "View Opportunities",
    
    // Footer
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.sectors": "Sectors",
    "footer.legal": "Legal",
    "footer.description": "Excellent accounting, auditing and tax consulting services for companies in Portugal.",
    "footer.accounting": "Accounting",
    "footer.taxConsulting": "Tax Consulting",
    "footer.hr": "Human Resources",
    "footer.audit": "Auditing",
    "footer.consulting": "Management Consulting",
    "footer.aboutUs": "About Us",
    "footer.team": "Team",
    "footer.careers": "Careers",
    "footer.news": "News",
    "footer.agriculture": "Agriculture",
    "footer.transport": "Transport",
    "footer.retail": "Retail",
    "footer.ecommerce": "E-commerce",
    "footer.construction": "Construction",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookies",
    "footer.gdpr": "GDPR",
    "footer.rights": "All rights reserved.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
